#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
unalias rm
unalias gcc

# Alias Nvim
alias vim=nvim

# GOPATH
export GOPATH=$HOME

# Set CDPATH
cdpath=( . $GOPATH/src/github.com $GOPATH/src/github.com/ivarg $GOPATH/src/github.com/TV4ads $GOPATH/src/github.com/TV4 $GOPATH/src )
export CDPATH=.:$GOPATH/src:$GOPATH/src/github.com:$GOPATH/src/github.com/TV4
export CDPATH

unsetopt share_history

export PATH=$PATH:$GOPATH/bin

# The next line updates PATH for the Google Cloud SDK.
if [ -f /Users/datamob/sdk/google-cloud-sdk/path.zsh.inc ]; then
  source '/Users/datamob/sdk/google-cloud-sdk/path.zsh.inc'
fi

# The next line enables shell command completion for gcloud.
if [ -f /Users/datamob/sdk/google-cloud-sdk/completion.zsh.inc ]; then
  source '/Users/datamob/sdk/google-cloud-sdk/completion.zsh.inc'
fi

# added by travis gem
[ -f /Users/datamob/.travis/travis.sh ] && source /Users/datamob/.travis/travis.sh
